CREATE TABLE IF NOT EXISTS todos(
	todo_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'TODOのID',
	title VARCHAR(32) NOT NULL COMMENT 'TODOのタイトル',
	status TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'TODOの完了フラグ(0:未完了、1:完了)',
	updated_by VARCHAR(12) NOT NULL DEFAULT 'python' COMMENT '最終更新者',
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最終更新日'
);