version: '3.9'

services:
  db:
    container_name: mysql8
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: python
      MYSQL_PASSWORD: python
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql/
    restart: always
  app:
    container_name: python
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
volumes:
  db-data: